apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tripviewer
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
spec:
  rules:
  - host: tripviewer.423f6b9aacaa4291af8e.eastasia.aksapp.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service: 
            name: tripviewer
            port: 
              number: 80