apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: tripviewer-secrets
  namespace: tripviewer-back
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: ""
    keyvaultName: "tripviewer-secrets"
    objects: |
      array:
        - |
          objectName: SQL-USER
          objectType: secret
          objectAlias: SQL_USER
          objectVersion: "cad136ed8b704121be1b710dac64f227"
        - |
          objectName: SQL-PASSWORD
          objectType: secret
          objectAlias: SQL_PASSWORD
          objectVersion: "742a923634cd49fa84762d652122f0fe"
    tenantId: "49949ab6-850f-4a3f-9050-f0bf973dc4f3"