apiVersion: v1
kind: Namespace
metadata:
  name: tripviewer-front
---
apiVersion: v1
kind: Namespace
metadata:
  name: tripviewer-back
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tripviewer
  namespace: tripviewer-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tripviewer
  template:
    metadata:
      labels:
        app: tripviewer
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: tripviewer
        image: registryexf6076.azurecr.io/tripviewer:1.0
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        ports:
        - containerPort: 80
        env:
        - name: TRIPS_API_ENDPOINT
          value: "http://trips.tripviewer-back.svc.cluster.local"
        - name: USERPROFILE_API_ENDPOINT
          value: "http://userprofile.tripviewer-back.svc.cluster.local"
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
---
apiVersion: v1
kind: Service
metadata:
  name: tripviewer
  namespace: tripviewer-front
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: tripviewer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trips
  namespace: tripviewer-back
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trips
  template:
    metadata:
      labels:
        app: trips
    spec:
      hostname: trips
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: trips
        image: registryexf6076.azurecr.io/trips:1.0
       # envFrom:
      # out as no longer using the secret YAML file
      #  - secretRef:
      #     name: secrets
        env:
        - name: SQL_SERVER
          value: "sqlserverexf6076.database.windows.net" 
        - name: SQL_DBNAME
          value: "mydrivingDB" 
        - name: PORT
          value: "80"
        - name: CONFIG_FILES_PATH
          value: "/secrets" 
        - name: OPENAPI_DOCS_URI
          value: "http://changeme"
        - name: DEBUG_LOGGING
          value: "true"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        ports:
        - containerPort: 80
          name: trips
        volumeMounts:
        - name: secrets-store01-inline
          mountPath: "/secrets"
          readOnly: true
      volumes:
      - name: secrets-store01-inline
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
           secretProviderClass: "tripviewer-secrets-yaml"
---
apiVersion: v1
kind: Service
metadata:
  name: trips
  namespace: tripviewer-back
spec:
  ports:
  - port: 80
  selector:
    app: trips

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-java
  namespace: tripviewer-back
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-java
  template:
    metadata:
      labels:
        app: user-java
    spec:
      hostname: user-java
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: user-java
        image: registryexf6076.azurecr.io/users:1.0
        #envFrom:
        #- secretRef:
        #   name: secrets
        env:
        - name: SQL_SERVER
          value: "sqlserverexf6076.database.windows.net" 
        - name: SQL_DBNAME
          value: "mydrivingDB" 
        - name: PORT
          value: "80"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        ports:
        - containerPort: 80
          name: user-java
        volumeMounts:
        - name: secrets-store01-inline
          mountPath: "/secrets"
          readOnly: true
      volumes:
      - name: secrets-store01-inline
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
           secretProviderClass: "tripviewer-secrets-yaml"
---
apiVersion: v1
kind: Service
metadata:
  name: user-java
  namespace: tripviewer-back
spec:
  ports:
  - port: 80
  selector:
    app: user-java

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: userprofile
  namespace: tripviewer-back
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userprofile
  template:
    metadata:
      labels:
        app: userprofile
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: userprofile
        image: registryexf6076.azurecr.io/userprofile:1.0
        #envFrom:
        #- secretRef:
        #   name: secrets
        env:
        - name: SQL_SERVER
          value: "sqlserverexf6076.database.windows.net" 
        - name: SQL_DBNAME
          value: "mydrivingDB" 
        - name: PORT
          value: "80"
        - name: CONFIG_FILES_PATH
          value: "/secrets" 
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        ports:
        - containerPort: 80
          name: userprofileport
        volumeMounts:
        - name: secrets-store01-inline
          mountPath: "/secrets"
          readOnly: true
      volumes:
      - name: secrets-store01-inline
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
           secretProviderClass: "tripviewer-secrets-yaml"
---
apiVersion: v1
kind: Service
metadata:
  name: userprofile
  namespace: tripviewer-back
spec:
  ports:
  - port: 80
  selector:
    app: userprofile
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: poi
  namespace: tripviewer-back
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poi
  template:
    metadata:
      labels:
        app: poi
    spec:
      hostname: poi
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: poi
        image: registryexf6076.azurecr.io/poi:1.0
        #envFrom:
        #- secretRef:
        #   name: secrets
        env: 
        - name: SQL_SERVER
          value: "sqlserverexf6076.database.windows.net" 
        - name: SQL_DBNAME
          value: "mydrivingDB" 
        - name: WEB_PORT
          value: "80"
        - name: CONFIG_FILES_PATH
          value: "/secrets" 
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        ports:
        - containerPort: 80
          name: poi
        volumeMounts:
        - name: secrets-store01-inline
          mountPath: "/secrets"
          readOnly: true
      volumes:
      - name: secrets-store01-inline
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
           secretProviderClass: "tripviewer-secrets-yaml"
---
apiVersion: v1
kind: Service
metadata:
  name: poi
  namespace: tripviewer-back
spec:
  ports:
  - port: 80
  selector:
    app: poi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: insurance-deployment
  namespace: tripviewer-back
  labels:
    deploy: insurance
spec:
  replicas: 2
  selector:
    matchLabels:
      app: insurance
  template:
    metadata:
      labels:
        app: insurance
    spec:
      containers:
      - image: registryexf6076.azurecr.io/insurance:1.0
        imagePullPolicy: Always
        name: insurance
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi

---
apiVersion: v1
kind: Service
metadata:
  name: insurance
  namespace: tripviewer-back
spec:
  type: ClusterIP
  selector:
    app: insurance
  ports:
  - protocol: TCP
    name: insurance-http
    port: 80
    targetPort: 8081